### ISSUE TITLE
HMR only working for last instance

### ISSUE THREAD

**Issue by pstoica** [webpack/style-loader#38]
I currently have some style entry points with one module each. Each module goes through a loader that returns a URL, then goes through style/url to added a <link>, but only the last entry point can accept and swap updates. The others say the page requires a reload. Weird setup, I know. There is also one commons chunk with the webpack runtime.

I can try testing this out in a more isolated environment, but let me know if anything looks wrong in the above that could cause this. Thanks!

**Comment by sokra** [comment]
You cannot have multiple webpack runtimes on a single page (or you need to provide alternative `output.jsonpFunction` and `output.hotUpdateFunction`).

And you cannot hot reload the entry point when having multiple entry points on a page.

Instead of doing `entry: { a: "a", b: "b" }` do `entry: { a: ["a"], b: ["b"] }`.

**Comment by pstoica** [comment]
That last one was the problem, thanks so much!
